#!/usr/bin/python3
# coding: utf-8

refsToFixManually = [
  'amfetamin',
  'andexanet alfa',
  'betametason',
  'botulinumtoksin',
  'budesonid',
  'bupropion',
  'deksametason',
  "glykopyrron",
  'imiquimod',
  'immunglobulin',
  'insulin',
  'interferon',
  'lidokain',
  'misoprostol',
  'morfin–skopolamin',
  'nintedanib',
  'pilokarpin',
  'tretinoin',
  'adstringerende',
  'aflibercept',
  'amfetamin',
  'aminopenicilliner',
  'betametason',
  'botulinumtoksin',
  'brinzolamid',
  'budesonid',
  'bupropion',
  'deksametason',
  'dorzolamid',
  'epitelceller',
  'follitropin',
  'imiquimod',
  'interferon',
  'ivmecillinam, trimetoprim',
  'kaliumpermanganat',
  'lidokain',
  'misoprostol',
  'omega-3',
  "oprim",
  'pilokarpin',
  'pyridoksin',
  'rimetoprim,',
  "selensulfid",
  'tretinoin',
  'trimet',
  'øyesalve',
]


refsToRemove = [
  'CJC-1295',
  'CNTO 530',
  'Ciraparantag',
  'EMP',
  'EPO-Fc',
  "EPO-mimetiske peptider",
  'GHRP-6',
  'meldonium',
  'SARM',
  'SERM',
  'trimetazidin',
  'alexamorelin',
  'amitryptilin',
  'anamorelin',
  'androstatriendion',
  'argon',
  'clostebol',
  'corticorelin',
  'cyklofenil,',
  'etakrynsyre',
  'formestan',
  'ghrelin',
  'gonadorelin',
  'hexarelin',
  'indapamid',
  'ipamorelin',
  'klenbuterol',
  'klortalidon',
  'klostebol',
  'kondroitin',
  'peginesatide',
  'pralmorelin',
  'selektive androgenreseptormodulatorer',
  'steinkulltjære',
  'tesamorelin',
  'testolakton.',
  'toremifen',
  'xenon',
  'zeranol',
  'zilpaterol',
]


refsCorrectionMapper = {
  "raloksifen,": "raloksifen",
  "aprepitant": "aprepitant og fosaprepitant",
  "askorbinsyre": "vitamin c (askorbinsyre)",
  "bupivakain": "bupivakain, levobupivakain",
  "cera": " metoksypolyetylenglykol-epoetin beta",
  "celeston chronodose": " betametason ",
  "desmopressin": "desmopressin, terlipressin",
  "dikloksacillin": "kloksacillin, dikloksacillin, flukloksacillin",
  "fenazon": " fenazon-koffein ",
  "fibrinogen": " humant fibrinogen",
  "ghrh": " sermorelin",
  "h2‑antagonister": " histamin h2‑antagonister",
  "kaliumsitrat": "kalium",
  "kloksacillin": "kloksacillin, dikloksacillin, flukloksacillin",
  "klorokin": "klorokin/hydroksyklorokin",
  "koffein": "koffein og koffeinsalter",
  "koriongonadotropin": "lutropin og koriongonadotropin",
  "makrogol": "makrogoler",
  "nsaid": "ikke‑steroide antiinflammatoriske midler (nsaid)",
  "podofyllotoksin": "podofyllotoksin/podofyllin",
  "pyridoksin": "vitamin b6 (pyridoksin)",
  "selektive østrogenreseptormodulatorer": "raloksifen",
  "teofyllin": "teofyllin og teofyllinsalter",
  "terlipressin": "desmopressin, terlipressin",
  "tiamin": "vitamin b1 (tiamin)",
  "viii": "faktor viii",
  "alfakalsidol": "vitamin d og analoger",
  "amilorid": "amilorid–hydroklortiazid",
  "aminoglykosid": "aminoglykosider",
  "anastrozol": "anastrozol, letrozol",
  "antitymocytt": "antitymocytt immunglobulin (kanin)",
  "aprepitant": "aprepitant og fosaprepitant",
  "bendroflumetiazid": "bendroflumetiazid (ev. med kalium)",
  "bupivakain": "bupivakain, levobupivakain",
  "cefalosporin": "cefalosporiner",
  "darbepoetin": "darbepoetin alfa",
  "desmopressin": "desmopressin, terlipressin",
  "desogestrel": "perorale gestagener",
  "dikloksacillin": "kloksacillin, dikloksacillin, flukloksacillin",
  "doksysyklin": "doksysyklin",
  "erytropoietiner": "erytropoietin og derivater",
  "etidronat": "bisfonater",
  "fenazon": "fenazon-koffein",
  "fibrinogen": "humant fibrinogen",
  "filgrastim": "filgrastim, lipefilgrastim, pegfilgrastim",
  "fluorokinolon": "fluorokinoloner",
  "fosaprepitant": "aprepitant og fosaprepitant",
  "ganciklovir": "ganciklovir/valganciklovir",
  "hostemiksturer": "diverse hostemiksturer o.l.",
  "hydroksyklorokin": "klorokin/hydroksyklorokin",
  "ikke-steroide antiinflammatoriske midler": "ikke‑steroide antiinflammatoriske midler (nsaid)",
  "immunglobulin": "immunglobuliner",
  "insulin": "insulin/insulinanaloger",
  "insulinanaloger": "insulin/insulinanaloger",
  "irinotekan": "irinotekan",
  "kaliumklorid": "kalium",
  "kanrenon": "kanrenoat",
  "kloksacillin": "kloksacillin, dikloksacillin, flukloksacillin",
  "klorokin": "klorokin/hydroksyklorokin",
  "klorokiner": "klorokin/hydroksyklorokin",
  "koffein": "koffein og koffeinsalter",
  "koriongonadotropin": "lutropin og koriongonadotropin",
  "lanreotid": "lanreotid, oktreotid",
  "letrozol": "anastrozol, letrozol",
  "levonorgestrel": "postkoital antikonsepsjon / angrepille",
  "makrogol": "makrogoler",
  "nandrolon": "androgene/anabole steroider",
  "naproxen ": "naproksen",
  "nikotinamid": "vitamin b3 (nikotinamid, nikotinsyre, niacin)",
  "oktreotid": "lanreotid, oktreotid",
  "olimumab": "golimumab",
  "pegfilgrastim": "filgrastim, lipefilgrastim, pegfilgrastim",
  "penicillin g": "benzylpenicillin",
  "protonpumpehemmer": "protonpumpehemmere",
  "tafluprost": "bimatoprost. latanoprost. tafluprost. travoprost",
  "teofyllin": "teofyllin og teofyllinsalter",
  "teriparatide": "teriparatide (hpth(1-34))", 
  "teriparatide ": "teriparatide (hpth(1-34))",
  "terlipressin": "desmopressin, terlipressin",
  "tiamin": "vitamin b1 (tiamin)",
  "trimetoprim-sulfametoksazol": "trimetoprim–sulfametoksazol",
}

# unclearWhats = {
#   "Doksysyklin": Fikset,
#   "Trimetoprim-sulfametoksazol": Matcher,
#   "azelainsyre": Fikset i QA, matcher der,
#   "escitalopram,": "Escitalopram," (matcher),
#   "galcanezumab": "Galcanezumab" (matcher),
#   "galcanezumab ": "Galcanezumab" (matcher),
#   "kaliumsitrat": "Kalium" (må rettes),
#   "organo-heparinoid": (matcher),
# }
